### ISSUE TITLE
How to use this module ?

### ISSUE THREAD

**Issue by adrianR84** [justb3a/processwire-padcouponcode#1]
Hello
I have padloper and I have followed all the steps for installing your plugin, my question is how to use this module in the front end ? Where am I suppose to add the coupon code to get the discount?

Thank you.

**Comment by justb3a** [comment]
The coupon code field should be added automatically to the `padorder` template, please verify this (Admin > Templates > `padorder`, fieldset `pad_customer` should contain the field `pad_couponcode`).

**Checkout Form**

The checkout form, which contains personal data (name, email, address, ..) now also contains a field where the coupon code could be filled in. I know, this is probably not the best place, but it was the easiest way to add it without touching the core module.

---

![form](https://user-images.githubusercontent.com/4669205/32720044-a86d30b4-c862-11e7-94cb-ddaef9220e6f.png)

**Comment by adrianR84** [comment]
Thank you for the info.
Yes, now is ok, I did not know exactly how is going to be and from the beginning, in padorder template. I have moved the field pad_couponcode out of the pad_customer fielset because I considered is not appropriate to be there and because of this I did not see any Coupon field in the front end.
Thank you for your help and for this module.

**Comment by adrianR84** [comment]
In regards to this module install, any idea why is not adding the coupon template to the PadCart config for product templates?
The code below looks correct but it,s not working ...

```
public function ___install() {
  $this->addFieldsAndTemplates();
  .............................
  // module PadCart: add template as product template
  $padCartData = $this->modules->getModuleConfigData('PadCart');
  $templateId = $this->template->id;
  if (!in_array($templateId, $padCartData['product_templates'])) {
    $padCartData['product_templates'][] = $templateId;
    $this->modules->saveModuleConfigData('PadCart', $padCartData);
  }
}
```

**Comment by justb3a** [comment]
Nope, I tested the installation process multiple times successfully. Could you please reinstall the module and debug the install method to figure out what went wrong?

```
public function ___install() {
  $this->addFieldsAndTemplates();
  .............................
  // module PadCart: add template as product template
  $padCartData = $this->modules->getModuleConfigData('PadCart');
  $templateId = $this->template->id;
+ var_dump(in_array($templateId, $padCartData['product_templates']));
  if (!in_array($templateId, $padCartData['product_templates'])) {
    $padCartData['product_templates'][] = $templateId;
    $this->modules->saveModuleConfigData('PadCart', $padCartData);
+   var_dump($this->modules->getModuleConfigData('PadCart'));
  }
+ exit;
}
```

**Comment by adrianR84** [comment]
It's because of line  $templateId = $this->template->id which return a null.
It's like for install() method, init() has not been called yet... 
I have fixed the problem changing that line to $templateId = $this->templates->get($this->templateName)->id;

Is it normal in install the init is called yet ?

**Comment by justb3a** [comment]
Thanks, it's fixed :)
